import os

BASE_DIR = os.getcwd()
MAIN_PATH = os.path.join(BASE_DIR, "backend", "app", "main.py")
DASHBOARD_DIR = os.path.join(BASE_DIR, "frontend", "dashboard")
DASHBOARD_PATH = os.path.join(DASHBOARD_DIR, "index.html")

os.makedirs(DASHBOARD_DIR, exist_ok=True)

with open(MAIN_PATH, "r", encoding="utf-8") as file:
    main_code = file.read()

if "from fastapi.middleware.cors import CORSMiddleware" not in main_code:
    main_code = main_code.replace(
        "from fastapi import FastAPI",
        "from fastapi import FastAPI\nfrom fastapi.middleware.cors import CORSMiddleware"
    )

cors_block = [
    "",
    "app.add_middleware(",
    "    CORSMiddleware,",
    "    allow_origins=[\"*\"],",
    "    allow_credentials=True,",
    "    allow_methods=[\"*\"],",
    "    allow_headers=[\"*\"],",
    ")",
    ""
]

cors_text = "\n".join(cors_block)

if "app.add_middleware(" not in main_code:
    marker = "BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), \"..\", \"..\"))"
    main_code = main_code.replace(marker, cors_text + "\n" + marker)

with open(MAIN_PATH, "w", encoding="utf-8") as file:
    file.write(main_code)

html_lines = [
    "<!DOCTYPE html>",
    "<html lang=\"en\">",
    "<head>",
    "  <meta charset=\"UTF-8\" />",
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />",
    "  <title>ForeverFlow AI Dashboard</title>",
    "  <style>",
    "    body {",
    "      margin: 0;",
    "      font-family: Arial, sans-serif;",
    "      background: #f7f4f1;",
    "      color: #1f1f1f;",
    "    }",
    "    .page {",
    "      max-width: 1200px;",
    "      margin: 0 auto;",
    "      padding: 32px;",
    "    }",
    "    .hero {",
    "      background: #ffffff;",
    "      border-radius: 24px;",
    "      padding: 32px;",
    "      box-shadow: 0 10px 30px rgba(0,0,0,0.08);",
    "      margin-bottom: 24px;",
    "    }",
    "    .hero h1 {",
    "      margin: 0;",
    "      font-size: 40px;",
    "    }",
    "    .hero p {",
    "      max-width: 850px;",
    "      line-height: 1.6;",
    "      color: #555;",
    "    }",
    "    .button {",
    "      border: none;",
    "      background: #1f1f1f;",
    "      color: #ffffff;",
    "      padding: 14px 22px;",
    "      border-radius: 999px;",
    "      cursor: pointer;",
    "      font-size: 15px;",
    "      font-weight: 700;",
    "    }",
    "    .button:hover {",
    "      opacity: 0.9;",
    "    }",
    "    .grid {",
    "      display: grid;",
    "      grid-template-columns: repeat(3, 1fr);",
    "      gap: 16px;",
    "      margin-bottom: 24px;",
    "    }",
    "    .card {",
    "      background: #ffffff;",
    "      border-radius: 20px;",
    "      padding: 20px;",
    "      box-shadow: 0 8px 24px rgba(0,0,0,0.06);",
    "    }",
    "    .metric {",
    "      font-size: 34px;",
    "      font-weight: 800;",
    "      margin-top: 8px;",
    "    }",
    "    .label {",
    "      color: #777;",
    "      font-size: 14px;",
    "    }",
    "    .section {",
    "      background: #ffffff;",
    "      border-radius: 24px;",
    "      padding: 24px;",
    "      box-shadow: 0 8px 24px rgba(0,0,0,0.06);",
    "      margin-bottom: 24px;",
    "    }",
    "    .section h2 {",
    "      margin-top: 0;",
    "    }",
    "    .timeline-item, .approval-item, .product-item, .evidence-item {",
    "      border: 1px solid #eee;",
    "      border-radius: 16px;",
    "      padding: 16px;",
    "      margin-bottom: 12px;",
    "      background: #fcfbfa;",
    "    }",
    "    .badge {",
    "      display: inline-block;",
    "      padding: 5px 10px;",
    "      border-radius: 999px;",
    "      font-size: 12px;",
    "      font-weight: 700;",
    "      background: #eee;",
    "      margin-right: 8px;",
    "    }",
    "    .high {",
    "      background: #ffe0e0;",
    "    }",
    "    .medium {",
    "      background: #fff0c2;",
    "    }",
    "    .low, .ready {",
    "      background: #dff5e4;",
    "    }",
    "    .review {",
    "      background: #ffe8d6;",
    "    }",
    "    .muted {",
    "      color: #666;",
    "      line-height: 1.5;",
    "    }",
    "    pre {",
    "      white-space: pre-wrap;",
    "      background: #1f1f1f;",
    "      color: #ffffff;",
    "      padding: 18px;",
    "      border-radius: 16px;",
    "      overflow-x: auto;",
    "    }",
    "    @media (max-width: 900px) {",
    "      .grid {",
    "        grid-template-columns: 1fr;",
    "      }",
    "    }",
    "  </style>",
    "</head>",
    "<body>",
    "  <div class=\"page\">",
    "    <div class=\"hero\">",
    "      <h1>ForeverFlow AI</h1>",
    "      <p><strong>Retail AI Control Tower for Shopify-Centred Fashion Operations.</strong></p>",
    "      <p>This dashboard runs a multi-agent collection readiness workflow across Shopify-style product data, inventory risk, returns intelligence, campaign readiness, RAG evidence, and governance approval controls.</p>",
    "      <button class=\"button\" onclick=\"runWorkflow()\">Run Collection Readiness Check</button>",
    "      <p id=\"status\" class=\"muted\"></p>",
    "    </div>",
    "",
    "    <div class=\"grid\" id=\"metrics\"></div>",
    "",
    "    <div class=\"section\">",
    "      <h2>Workflow Timeline</h2>",
    "      <div id=\"timeline\" class=\"muted\">Run the workflow to see the timeline.</div>",
    "    </div>",
    "",
    "    <div class=\"section\">",
    "      <h2>Approval Queue</h2>",
    "      <div id=\"approvals\" class=\"muted\">Run the workflow to see approval items.</div>",
    "    </div>",
    "",
    "    <div class=\"section\">",
    "      <h2>Product Agent Results</h2>",
    "      <div id=\"products\" class=\"muted\">Run the workflow to see product-level decisions.</div>",
    "    </div>",
    "",
    "    <div class=\"section\">",
    "      <h2>RAG Evidence Viewer</h2>",
    "      <div id=\"evidence\" class=\"muted\">Run the workflow to see trusted policy evidence.</div>",
    "    </div>",
    "",
    "    <div class=\"section\">",
    "      <h2>Raw API Response</h2>",
    "      <pre id=\"raw\">Run the workflow to see the full backend response.</pre>",
    "    </div>",
    "  </div>",
    "",
    "  <script>",
    "    async function runWorkflow() {",
    "      const status = document.getElementById('status');",
    "      status.textContent = 'Running multi-agent collection readiness workflow...';",
    "",
    "      try {",
    "        const response = await fetch('http://127.0.0.1:8000/run-collection-readiness', {",
    "          method: 'POST',",
    "          headers: { 'Content-Type': 'application/json' },",
    "          body: JSON.stringify({ collection_name: 'Winter Occasionwear' })",
    "        });",
    "",
    "        if (!response.ok) {",
    "          throw new Error('Backend returned status ' + response.status);",
    "        }",
    "",
    "        const data = await response.json();",
    "        status.textContent = 'Workflow completed successfully.';",
    "        renderMetrics(data);",
    "        renderTimeline(data.workflow_timeline || []);",
    "        renderApprovals(data.approval_queue || []);",
    "        renderProducts(data.agent_results || []);",
    "        renderEvidence(data.rag_evidence || []);",
    "        document.getElementById('raw').textContent = JSON.stringify(data, null, 2);",
    "      } catch (error) {",
    "        status.textContent = 'Error: ' + error.message + '. Make sure FastAPI is running on http://127.0.0.1:8000';",
    "      }",
    "    }",
    "",
    "    function renderMetrics(data) {",
    "      const impact = data.business_impact || {};",
    "      const metrics = [",
    "        ['Products Checked', data.products_checked],",
    "        ['Issues Found', data.issues_found],",
    "        ['High-Risk Items', data.high_risk_items],",
    "        ['Approval Required', data.approval_required],",
    "        ['Auto Approved', data.auto_approved],",
    "        ['Estimated Hours Saved', impact.estimated_hours_saved]",
    "      ];",
    "",
    "      document.getElementById('metrics').innerHTML = metrics.map(item => `",
    "        <div class=\"card\">",
    "          <div class=\"label\">${item[0]}</div>",
    "          <div class=\"metric\">${item[1] ?? '-'}</div>",
    "        </div>",
    "      `).join('');",
    "    }",
    "",
    "    function renderTimeline(items) {",
    "      document.getElementById('timeline').innerHTML = items.map(item => `",
    "        <div class=\"timeline-item\">",
    "          <span class=\"badge ready\">Step ${item.step}</span>",
    "          <strong>${item.name}</strong>",
    "          <p class=\"muted\">${item.description}</p>",
    "        </div>",
    "      `).join('');",
    "    }",
    "",
    "    function renderApprovals(items) {",
    "      if (items.length === 0) {",
    "        document.getElementById('approvals').innerHTML = '<p class=\"muted\">No approval items. All products are ready.</p>';",
    "        return;",
    "      }",
    "",
    "      document.getElementById('approvals').innerHTML = items.map(item => `",
    "        <div class=\"approval-item\">",
    "          <span class=\"badge ${item.risk_level}\">${item.risk_level.toUpperCase()}</span>",
    "          <strong>${item.title}</strong>",
    "          <p class=\"muted\">${item.requested_action}</p>",
    "          <ul>${item.reasons.map(reason => `<li>${reason}</li>`).join('')}</ul>",
    "        </div>",
    "      `).join('');",
    "    }",
    "",
    "    function renderProducts(items) {",
    "      document.getElementById('products').innerHTML = items.map(item => {",
    "        const content = item.product_content_agent;",
    "        const inventory = item.inventory_risk_agent;",
    "        const returns = item.returns_intelligence_agent;",
    "        const campaign = item.campaign_readiness_agent;",
    "        const governance = item.governance_agent;",
    "        return `",
    "          <div class=\"product-item\">",
    "            <h3>${item.title}</h3>",
    "            <span class=\"badge\">Content Score: ${content.content_score}</span>",
    "            <span class=\"badge ${inventory.risk_level}\">Inventory: ${inventory.risk_level}</span>",
    "            <span class=\"badge ${returns.risk_level}\">Returns: ${returns.risk_level}</span>",
    "            <span class=\"badge ${governance.status === 'ready' ? 'ready' : 'review'}\">${governance.decision}</span>",
    "            <p class=\"muted\"><strong>Campaign:</strong> ${campaign.recommendation}</p>",
    "            <p class=\"muted\"><strong>Draft Copy:</strong> ${campaign.draft_campaign_copy}</p>",
    "            <p class=\"muted\"><strong>Issues:</strong> ${content.issues.length ? content.issues.join(', ') : 'None'}</p>",
    "          </div>",
    "        `;",
    "      }).join('');",
    "    }",
    "",
    "    function renderEvidence(items) {",
    "      document.getElementById('evidence').innerHTML = items.map(item => `",
    "        <div class=\"evidence-item\">",
    "          <strong>${item.source}</strong>",
    "          <p class=\"muted\">${item.evidence}</p>",
    "        </div>",
    "      `).join('');",
    "    }",
    "  </script>",
    "</body>",
    "</html>"
]

with open(DASHBOARD_PATH, "w", encoding="utf-8") as file:
    file.write("\n".join(html_lines))

print("Dashboard created successfully.")
print("Dashboard path:", DASHBOARD_PATH)
print("CORS enabled in backend/app/main.py")